//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Content()
        {
            this.ContentAssigns = new HashSet<ContentAssign>();
        }
    
        public int CTID { get; set; }
        public string CTName { get; set; }
        public string CTDescription { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string StudentID { get; set; }
        public string Name { get; set; }
        public string ContentType { get; set; }
        public byte[] Data { get; set; }
        public string Name2 { get; set; }
        public string ContentType2 { get; set; }
        public byte[] Data2 { get; set; }
        public string TopicID { get; set; }
    
        public virtual Faculty Faculty { get; set; }
        public virtual Student Student { get; set; }
        public virtual Topic Topic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentAssign> ContentAssigns { get; set; }
    }
}
