//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingManager
    {
        public string MMID { get; set; }
        public string MMName { get; set; }
        public string MMAddress { get; set; }
        public string MMEmail { get; set; }
        public string MMPhone { get; set; }
        public string UserName { get; set; }
    }
}
