//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarketingCoordinator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MarketingCoordinator()
        {
            this.ContentAssigns = new HashSet<ContentAssign>();
        }
    
        public string MCID { get; set; }
        public string MCName { get; set; }
        public string MCAddress { get; set; }
        public string MCPhone { get; set; }
        public Nullable<int> FacultyID { get; set; }
        public string UserName { get; set; }
        public string MCEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContentAssign> ContentAssigns { get; set; }
        public virtual Faculty Faculty { get; set; }
    }
}
