//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebEnterprise.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class G5EnterpriseDBEntities : DbContext
    {
        public G5EnterpriseDBEntities()
            : base("name=G5EnterpriseDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Content> Contents { get; set; }
        public virtual DbSet<ContentAssign> ContentAssigns { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<Guest> Guests { get; set; }
        public virtual DbSet<MarketingCoordinator> MarketingCoordinators { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<Topic> Topics { get; set; }
        public virtual DbSet<MarketingManager> MarketingManagers { get; set; }
    }
}
